name: CI
on: push

jobs:
  test-rate-liimiting:
    runs-on: ubuntu-latest
    container: python:3.8

    services:
      redis:
        image: redis

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: start FastAPI
        

      - name: Connect to Redis
        run: node client.js
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379